base_url = "https://wispl.github.io/"
title = "Archive"
description = "Archive"

compile_sass = false
build_search_index = false
minify_html = true

taxonomies = [
    { name = "tags", feed = false, render = false},
]

[markdown]
github_alerts = true
bottom_footnotes = true
definition_list = true

[markdown.highlighting]
style = "class"
light_theme = "kanagawa-lotus"
dark_theme = "kanagawa-dragon"

[extra]
nav_items = [
	{ url = "/", name = "HOME" },
	{ url = "/archive", name = "ARCHIVE" },
	{ url = "/notes", name = "NOTES" },
	{ url = "/about", name = "ABOUT" }
]
