base_url = "https://wispl.github.io/"
title = "Archive"
description = "Archive"

compile_sass = false
build_search_index = false
minify_html = true

taxonomies = [
    { name = "tags", feed = false, render = false},
]

[markdown]
github_alerts = true
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["syntax"]

highlight_themes_css = [
  { theme = "kanagawa-dragon", filename = "syntax-dark.css" },
  { theme = "kanagawa-lotus", filename = "syntax-light.css" },
]

[extra]
nav_items = [
	{ url = "/", name = "HOME" },
	{ url = "/archive", name = "ARCHIVE" },
	{ url = "/notes", name = "NOTES" },
	{ url = "/about", name = "ABOUT" }
]
